# Generated by Django 5.0.6 on 2024-10-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='sponsorname',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Sponsors',
        ),
    ]
